import type { Category, Post, TrendingArticle } from "./types/generalTypes";

export const headlines: string[] = [
  "New trade policy approved by Senate committee",
  "Department of Health announces nationwide initiative",
  "Quarterly economic growth exceeds projections",
  "International climate summit reaches landmark agreement",
  "Federal reserve hints at interest rate stabilization",
  "New infrastructure bill includes coastal rail expansion",
  "Cybersecurity task force to implement new standards",
];

// Categories definitions
const politicsCategory: Category = {
  _id: "cat-politics",
  name: "Politics",
  slug: "politics",
  description: "Political news, legislation, and updates.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const businessCategory: Category = {
  _id: "cat-business",
  name: "Business",
  slug: "business",
  description: "Financial markets, economics, and commerce.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const healthCategory: Category = {
  _id: "cat-health",
  name: "Health",
  slug: "health",
  description: "Public health, research, and medical updates.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const environmentCategory: Category = {
  _id: "cat-environment",
  name: "Environment",
  slug: "environment",
  description: "Climate change, conservation, and green energy.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const transitCategory: Category = {
  _id: "cat-transit",
  name: "Transit",
  slug: "transit",
  description: "Infrastructure, transportation, and public works.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const diplomacyCategory: Category = {
  _id: "cat-diplomacy",
  name: "Diplomacy",
  slug: "diplomacy",
  description: "International relations, summits, and foreign policy.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const educationCategory: Category = {
  _id: "cat-education",
  name: "Education",
  slug: "education",
  description: "Academic updates, educational policies, and literacy.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const technologyCategory: Category = {
  _id: "cat-technology",
  name: "Technology",
  slug: "technology",
  description: "Cybersecurity, tech regulation, and innovation.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

const communitiesCategory: Category = {
  _id: "cat-communities",
  name: "Communities",
  slug: "communities",
  description: "Urban development, parks, and local initiatives.",
  isActive: true,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
};

// Posts definitions
export const heroArticle: Post = {
  _id: "post-hero-1",
  title: "Historic Reform Bill Navigates Final Senate Vote Amid Growing Consensus",
  slug: "historic-reform-bill-navigates-final-senate-vote",
  excerpt: "Bipartisan efforts lead to a landmark decision that could reshape national infrastructure and public funding for the next decade.",
  content: "Full content of the historic reform bill vote details...",
  featuredImage: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80",
  category: politicsCategory,
  author: "Sarah Jenkins",
  status: "published",
  views: 1420,
  readingTime: "12 min read",
  isFeatured: true,
  publishedAt: "2026-07-13T08:00:00Z",
  createdAt: "2026-07-13T08:00:00Z",
  updatedAt: "2026-07-13T08:00:00Z",
};

export const subHeroArticles: Post[] = [
  {
    _id: "post-sub-1",
    title: "Markets React to New Federal Trade Adjustments",
    slug: "markets-react-to-new-federal-trade-adjustments",
    excerpt: "Wall street responds immediately to adjusted tariffs and trade regulations.",
    content: "Full market response details...",
    featuredImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=600&q=80",
    category: businessCategory,
    author: "Jameson Cox",
    status: "published",
    views: 890,
    readingTime: "5 min read",
    isFeatured: false,
    publishedAt: "2 hours ago", // matches home page text display format
    createdAt: "2026-07-13T09:00:00Z",
    updatedAt: "2026-07-13T09:00:00Z",
  },
  {
    _id: "post-sub-2",
    title: "National Health Initiative Targets Remote Access",
    slug: "national-health-initiative-targets-remote-access",
    excerpt: "Federal program funds telehealth and diagnostics for rural areas.",
    content: "Full health initiative details...",
    featuredImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=600&q=80",
    category: healthCategory,
    author: "Elena Rodriguez",
    status: "published",
    views: 750,
    readingTime: "6 min read",
    isFeatured: false,
    publishedAt: "4 hours ago",
    createdAt: "2026-07-13T07:00:00Z",
    updatedAt: "2026-07-13T07:00:00Z",
  },
  {
    _id: "post-sub-3",
    title: "Offshore Wind Projects Gain Multi-State Approval",
    slug: "offshore-wind-projects-gain-multi-state-approval",
    excerpt: "Eastern seaboard states align on major offshore turbine installations.",
    content: "Full offshore wind report...",
    featuredImage: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=600&q=80",
    category: environmentCategory,
    author: "Marcus Thorne",
    status: "published",
    views: 620,
    readingTime: "8 min read",
    isFeatured: false,
    publishedAt: "6 hours ago",
    createdAt: "2026-07-13T05:00:00Z",
    updatedAt: "2026-07-13T05:00:00Z",
  },
  {
    _id: "post-sub-4",
    title: "Infrastructure Bill Includes Coastal Rail Expansion",
    slug: "infrastructure-bill-includes-coastal-rail-expansion",
    excerpt: "High-speed rail investments approved for major transit corridors.",
    content: "Full rail expansion plans...",
    featuredImage: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=600&q=80",
    category: transitCategory,
    author: "Dr. Alistair Vance",
    status: "published",
    views: 1100,
    readingTime: "10 min read",
    isFeatured: false,
    publishedAt: "8 hours ago",
    createdAt: "2026-07-13T03:00:00Z",
    updatedAt: "2026-07-13T03:00:00Z",
  },
];

export const latestNews: Post[] = [
  {
    _id: "post-latest-1",
    title: "Joint Communiqué Issued Following Regional Summit",
    slug: "joint-communique-issued-following-regional-summit",
    excerpt: "Leaders from seven nations agree on a unified approach to maritime security and cross-border environmental protection...",
    content: "Full communiqué summary...",
    featuredImage: "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?auto=format&fit=crop&w=600&q=80",
    category: diplomacyCategory,
    author: "Sarah Jenkins",
    status: "published",
    views: 480,
    readingTime: "12 min read",
    isFeatured: false,
    publishedAt: "2026-07-13T08:30:00Z",
    createdAt: "2026-07-13T08:30:00Z",
    updatedAt: "2026-07-13T08:30:00Z",
  },
  {
    _id: "post-latest-2",
    title: "Grant Programs Announced for Digital Literacy in Schools",
    slug: "grant-programs-announced-for-digital-literacy-in-schools",
    excerpt: "The Department of Education launches a $500M initiative to provide high-speed fiber and tablet computers to rural districts...",
    content: "Full digital literacy grant outline...",
    featuredImage: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80",
    category: educationCategory,
    author: "Marcus Thorne",
    status: "published",
    views: 310,
    readingTime: "8 min read",
    isFeatured: false,
    publishedAt: "2026-07-13T07:15:00Z",
    createdAt: "2026-07-13T07:15:00Z",
    updatedAt: "2026-07-13T07:15:00Z",
  },
  {
    _id: "post-latest-3",
    title: "Cybersecurity Task Force to Implement New Standards",
    slug: "cybersecurity-task-force-to-implement-new-standards",
    excerpt: "New protocols for government contractors aim to secure the supply chain against increasing sophisticated digital threats...",
    content: "Full cybersecurity specs...",
    featuredImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80",
    category: technologyCategory,
    author: "Dr. Alistair Vance",
    status: "published",
    views: 950,
    readingTime: "15 min read",
    isFeatured: false,
    publishedAt: "2026-07-13T06:00:00Z",
    createdAt: "2026-07-13T06:00:00Z",
    updatedAt: "2026-07-13T06:00:00Z",
  },
  {
    _id: "post-latest-4",
    title: "Urban Development Fund Approves 12 New Green Spaces",
    slug: "urban-development-fund-approves-12-new-green-spaces",
    excerpt: "Major cities to receive funding for pedestrian-friendly zones and community parks to improve air quality and social...",
    content: "Full green space approvals list...",
    featuredImage: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
    category: communitiesCategory,
    author: "Elena Rodriguez",
    status: "published",
    views: 540,
    readingTime: "6 min read",
    isFeatured: false,
    publishedAt: "2026-07-13T04:30:00Z",
    createdAt: "2026-07-13T04:30:00Z",
    updatedAt: "2026-07-13T04:30:00Z",
  },
];

export const trendingArticles: TrendingArticle[] = [
  {
    id: "01",
    category: "Economics",
    title: "The 2024 Budget Breakdown: What You Need to Know",
  },
  {
    id: "02",
    category: "Security",
    title: "New Travel Regulations for International Tech Exports",
  },
  {
    id: "03",
    category: "Social Policy",
    title: "Housing Crisis: Federal Subsidies Explained",
  },
  {
    id: "04",
    category: "Energy",
    title: "Energy Independence: The Nuclear Option Returns",
  },
];

export const politicsArticles: Post[] = [
  {
    _id: "post-pol-1",
    title: "Interview: The Future of Federalism",
    slug: "interview-the-future-of-federalism",
    excerpt: "Exclusive Q&A with political scientists on national balance of power.",
    content: "Full interview text...",
    featuredImage: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=600&q=80",
    category: politicsCategory,
    author: "Sarah Jenkins",
    status: "published",
    views: 310,
    readingTime: "8 min read",
    isFeatured: false,
    publishedAt: "2026-07-12T12:00:00Z",
    createdAt: "2026-07-12T12:00:00Z",
    updatedAt: "2026-07-12T12:00:00Z",
  },
  {
    _id: "post-pol-2",
    title: "Voter Turnout Hits Record Highs in Primaries",
    slug: "voter-turnout-hits-record-highs-in-primaries",
    excerpt: "Higher engagement noted across all demographics in recent primary states.",
    content: "Full primary turnout stats...",
    featuredImage: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=600&q=80",
    category: politicsCategory,
    author: "Jameson Cox",
    status: "published",
    views: 450,
    readingTime: "4 min read",
    isFeatured: false,
    publishedAt: "2026-07-12T10:00:00Z",
    createdAt: "2026-07-12T10:00:00Z",
    updatedAt: "2026-07-12T10:00:00Z",
  },
  {
    _id: "post-pol-3",
    title: "Support for New Climate Initiative Surges",
    slug: "support-for-new-climate-initiative-surges",
    excerpt: "Public surveys point to rising support for carbon reduction targets.",
    content: "Full climate support details...",
    featuredImage: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80",
    category: politicsCategory,
    author: "Marcus Thorne",
    status: "published",
    views: 680,
    readingTime: "5 min read",
    isFeatured: false,
    publishedAt: "2026-07-12T09:00:00Z",
    createdAt: "2026-07-12T09:00:00Z",
    updatedAt: "2026-07-12T09:00:00Z",
  },
];
